name: Terraform AWS EC2 Deployment

on:
  push:
    branches:
      - development  # Runs when changes are pushed to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  terraform:
    name: Deploy EC2 with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: terraform


      - name: Output EC2 Public IP
        run: terraform output public_ip
        working-directory: terraform
      
      - name: Get EC2 Public IP
        id: ec2-ip
        run: echo "EC2_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
        working-directory: terraform

      - name: Wait for EC2 SSH to be Ready
        run: |
          echo "Waiting for EC2 to be accessible..."
          sleep 60  # Wait for EC2 to boot up

      - name: Deploy Python Module to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Clone the Python module from GitHub
            git clone https://github.com/pentaai5/stock_analysis.git /home/ec2-user/pentaai5
            
            # Change to the module directory
            cd /home/ec2-user/pentaai5
            
            # Install dependencies
            pip3 install -r requirements.txt
            
            # Run the Python module (adjust based on your module)
            python3 StrategyTester.py name='STOCK_TICKER' start='2024-01-01' end='2025-01-01' long_only='True/False'
            
            # For later run
            #python BollingerBandTester.py name='6758.T' start='2024-01-01' end='2025-01-01' long_only='False'
